export const LOGIN_AUTH = 'LOGIN_AUTH';
export const PASSWORD_AUTH = 'PASSWORD_AUTH';
export const USER_AUTH_STARTED = 'USER_AUTH_STARTED';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';
export const USER_AUTH_EXIT = 'USER_AUTH_EXIT';