export const GET_DATA_SELECT_FUEL = 'GET_DATA_SELECT_FUEL';
export const CLEAR_DATA_SELECT_FUEL = 'CLEAR_DATA_SELECT_FUEL';
export const GET_PARAMS_GAS_FUEL = 'GET_PARAMS_GAS_FUEL';
export const GET_TYPE_PAY = 'GET_TYPE_PAY';