export const START_NEW_TRANSACTION = 'START_NEW_TRANSACTION';
export const START_NEW_TRANSACTION_ERROR = 'START_NEW_TRANSACTION_ERROR';

export const START_PAYMENT = 'START_PAYMENT';
export const START_PAYMENT_ERROR = 'START_PAYMENT_ERROR';

export const GET_WIDGET_STARTED = 'GET_WIDGET_STARTED';
export const GET_WIDGET_SUCCESS = 'GET_WIDGET_SUCCESS';
export const GET_WIDGET_ERROR = 'GET_WIDGET_ERROR';
export const GET_WIDGET_CLEAR = 'GET_WIDGET_CLEAR';

export const GET_PAYMENT = 'GET_PAYMENT';

export const PAYMENT_CHOOSE_PAY = 'PAYMENT_CHOOSE_PAY';

export const PAYMENT_PAY_STARTED = 'PAYMENT_PAY_STARTED';
export const PAYMENT_PAY_SUCCESS = 'PAYMENT_PAY_SUCCESS';
export const PAYMENT_PAY_ERROR = 'PAYMENT_PAY_ERROR';

export const PAYMENT_FINISH_STARTED = 'PAYMENT_FINISH_STARTED';
export const PAYMENT_FINISH_SUCCESS = 'PAYMENT_FINISH_SUCCESS';
export const PAYMENT_FINISH_ERROR = 'PAYMENT_FINISH_ERROR';

export const GET_CART = 'GET_CART';
export const CLEAR_CART = 'CLEAR_CART';