export const GET_ORDER_FUEL = 'GET_ORDER_FUEL';
export const GET_ORDER_DATA = 'GET_ORDER_DATA';
export const CLEAR_ORDER_DATA = 'CLEAR_ORDER_DATA';
export const GET_ERROR_DATA_ORDER = 'GET_ERROR_DATA_ORDER';
export const GET_SELECT_DATA_FUEL = 'GET_SELECT_DATA_FUEL';