export const GET_STATUS_DEVICE_STARTED = 'GET_STATUS_DEVICE';
export const GET_STATUS_DEVICE_SUCCESS = 'GET_STATUS_DEVICE_SUCCESS';
export const GET_STATUS_DEVICE_FAILURE= 'GET_STATUS_DEVICE_FAILURE';